- hosts: webserver
  become: true
  tasks:
    - name: install apache
      apt: name=apache2 state=present update_cache=yes
    - name: deleted index.html
      file: path=/var/www/html/index.html state=absent
      notify: restart apache2
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
- hosts: app01
  become: true
  tasks:
    - name: set up index.html for first web server
      copy: >-
        content="<html><header><title>Welcome to Server 1</title>"
        dest=/var/www/html/index.html mode=0644
  notify: restart apache2
  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
- hosts: app02
  become: true
  tasks:
    - name: set up index.html for second web server
      copy: >-
        content="<html><header><title>Welcome to Server
        2</title></header><body>Hello from Server 2!</body></html>"
        dest=/var/www/html/index.html mode=0644
  notify: restart apache2
  handlers:
    - name: restart apache2
  service: name=apache2 state=restarted


# Ref: https://linuxhint.com/ansible-tutorial-beginners/
# In the above code, first apache2 is getting installed on both app01 and app02. Then the /var/www/html/index.html is deleted from both of the servers.
# Next individually app01 and app02 is given separate index.html. The reason for the separate html is to make sure they are distinguishable. The handlers restart the apache2 server after every change.
